name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-os-boost:
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-latest, macos-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: autoreconf --install
    - name: Configure
      run: ./configure
    - name: make
      run: make
    - name: test
      run: ./test.sh
